#!/bin/sh
##==================================================================##
 #
 # Data acquisition script for the sequential implementation of
 # QuickSort
 #
 # Frank Blanning <frankgou@ece.auth.gr>
 # AEM: 6698
 # Time-stamp: <2018-10-25>
 #
##==================================================================##

file="$1"

touch $file

for q in {16..24}
do
    echo "$q \c" >> $file
    for r in {1..5}
    do
	echo "\b," $(./qsort $q ) "\c" >> $file
    done
    echo "\b" >> $file
done
