#!/bin/sh
##==================================================================##
 #
 # Data acquisition script for the pthread implementation of QuickSort
 #
 # Frank Blanning <frankgou@ece.auth.gr>
 # AEM: 6698
 # Time-stamp: <2018-10-25>
 #
##==================================================================##

file="$1"

touch $file;

for q in {16..24}
do
    for t in {1..8}
    do
	echo "$q, $t \c" >> $file;
	for r in {1..5}
	do
	    sleep 0.5;
	    echo "\b," $(./qsort-pth $q $t) "\c" >> $file;
	done
	echo "\b;" >> $file;
    done
done
